const status=document.querySelector('#status');
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,options){const response=await fetch(url,options);if(response.status===401||response.status===403)location.href='/welcome';if(!response.ok)throw new Error((await response.json()).detail||'Request failed');return response.status===204?null:response.json()}
function bars(target,values){const entries=Object.entries(values||{}).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...entries.map(x=>x[1]));document.querySelector(target).innerHTML=entries.length?entries.map(([name,value])=>`<div class="bar"><span>${escapeHtml(name)}</span><i style="--size:${value/max}"></i><b>${value}</b></div>`).join(''):'<p class="empty">No activity recorded yet.</p>'}
async function loadOverview(){const data=await api('/api/admin/overview'),cards=[['Total users',data.total_users],['Active today',data.active_today],['Active this week',data.active_week],['Product events',data.event_count]];document.querySelector('#metrics').innerHTML=cards.map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join('');document.querySelector('#metrics').removeAttribute('aria-busy');bars('#countries',data.countries);bars('#features',data.features)}
async function loadUsers(search=''){const data=await api(`/api/admin/users?search=${encodeURIComponent(search)}`);document.querySelector('#users').innerHTML=data.users.length?data.users.map(user=>`<tr><td><strong>${escapeHtml(user.email)}</strong><small>${escapeHtml(user.user_id)}</small></td><td>${escapeHtml(user.country)}</td><td>${new Date(user.created_at).toLocaleDateString()}</td><td><span class="state ${escapeHtml(user.account_status)}">${escapeHtml(user.account_status)}</span></td><td>${user.account_status==='active'?`<button data-disable="${escapeHtml(user.user_id)}">Disable</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No matching users.</td></tr>'}
document.querySelector('#search').addEventListener('input',event=>loadUsers(event.target.value).catch(error=>status.textContent=error.message));
document.querySelector('#users').addEventListener('click',async event=>{const uid=event.target.dataset.disable;if(!uid||!confirm('Disable this account? The user will no longer be able to sign in.'))return;await api(`/api/admin/users/${encodeURIComponent(uid)}/disable`,{method:'POST'});await Promise.all([loadOverview(),loadUsers(document.querySelector('#search').value)])});
document.querySelector('#logout').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'});location.href='/welcome'});
Promise.all([loadOverview(),loadUsers()]).catch(error=>status.textContent=error.message);
