/* Historical series are separate from current evidence and never fill missing values. */
(() => {
  const root=document.createElement('section');root.id='historical-evidence';root.className='epi-panel';
  document.querySelector('#visuals').after(root);
  root.innerHTML='<small>HISTORICAL EVIDENCE</small><h2>Past events. Traceable evidence.</h2><p>Explore the available archive separately from current surveillance. Different outbreaks and reporting frequencies are not joined into one trend.</p><div class="epi-controls"><label>Disease <select id="history-disease"><option value="measles">Measles</option><option value="ebola">Ebola</option><option value="cholera">Cholera (legacy WHO annual)</option><option value="measles_annual">Measles (WHO via OWID annual)</option><option value="cholera_annual">Cholera (WHO via OWID annual)</option></select></label><label>Country or outbreak scope <select id="history-country"></select></label><label>From year <input id="history-start" type="number" min="1900" max="2100" value="2010"></label><label>To year <input id="history-end" type="number" min="2010" max="2100" value="2026"></label><button id="history-load">Apply years</button></div><p id="history-status" role="status">Loading historical catalog…</p><div id="history-result"></div>';
  const css=document.createElement('style');css.textContent='#historical-evidence{max-width:1280px;margin:48px auto;scroll-margin-top:110px}#historical-evidence select{padding:12px;border:1px solid #cbd8d1;border-radius:8px;max-width:100%}#historical-evidence label{display:grid;gap:8px;max-width:100%}#historical-evidence input{width:110px}.history-chart{width:100%;height:auto;min-height:230px}.history-chart text{font:13px system-ui;fill:#153d31}.history-bars{display:grid;gap:12px}.history-bar{background:#148b68;height:10px;border-radius:4px}.history-actions{display:flex;gap:12px;flex-wrap:wrap}';document.head.append(css);
  const esc=v=>safe(String(v??'Not stated'));let meta,data,serial=0;
  const el=id=>document.getElementById('history-'+id);
  async function load(){
    const run=++serial;el('status').textContent='Loading source-backed history…';el('result').replaceChildren();
    try{
      const params=new URLSearchParams({country:el('country').value,start:el('start').value,end:el('end').value});
      const r=await fetch('/api/history/'+el('disease').value+'?'+params);if(!r.ok)throw Error('Select an available country and a valid year range.');
      const result=await r.json();if(run!==serial)return;data=result;draw();
    }catch(e){if(run===serial)el('status').textContent=e.message}
  }
  function scope(){const d=meta[el('disease').value];el('country').replaceChildren(...d.countries.map(c=>new Option(c.name,c.code)));const preferred=el('disease').value.startsWith('measles')?'USA':el('disease').value.startsWith('cholera')?'NGA':'ALL';if(d.countries.some(c=>c.code===preferred))el('country').value=preferred;load()}
  function draw(){
    const rows=data.points, valid=rows.filter(p=>p.value!=null), maximum=Math.max(1,...valid.map(p=>p.value));
    el('status').textContent=valid.length+' reported observations · '+data.frequency+' · selected data '+(valid[0]?.period||'none')+' to '+(valid.at(-1)?.period||'none');
    let chart='';
    if(data.frequency==='outbreak'){
      chart='<div class="history-bars">'+valid.map(p=>'<div><span>'+esc(p.label)+' · '+fmt(p.value)+' cases</span><div class="history-bar" style="width:'+Math.max(.4,100*p.value/maximum)+'%"></div><small>'+esc(p.species)+'</small></div>').join('')+'</div>';
    }else if(valid.length){
      const timestamp=p=>Date.parse(p.period+(data.frequency==='monthly'?'-01':'-01-01'));
      const first=timestamp(rows[0]),span=Math.max(1,timestamp(rows.at(-1))-first),x=p=>70+760*(timestamp(p)-first)/span,y=p=>260-210*p.value/maximum;
      const grid=[0,.5,1].map(f=>'<line x1="70" x2="830" y1="'+(260-210*f)+'" y2="'+(260-210*f)+'" stroke="#d8e2db"/><text x="60" y="'+(265-210*f)+'" text-anchor="end">'+fmt(Math.round(maximum*f))+'</text>').join('');
      const peaks=[valid.reduce((a,b)=>a.value>b.value?a:b),valid[0],valid.at(-1)],labels=[];for(const p of peaks){if(!labels.some(q=>Math.abs(x(p)-x(q))<100&&Math.abs(y(p)-y(q))<45))labels.push(p)}
      const marks=valid.map((p,i)=>'<g tabindex="0" role="button" data-history-point="'+i+'" aria-label="'+esc(p.period+': '+fmt(p.value)+' '+data.unit)+'"><title>'+esc(p.period)+': '+fmt(p.value)+' '+esc(data.unit)+'</title><line x1="'+x(p)+'" x2="'+x(p)+'" y1="260" y2="'+y(p)+'" stroke="#16815d" stroke-width="2"/><circle r="8" fill="transparent" cx="'+x(p)+'" cy="'+y(p)+'"/><circle r="3" fill="#16815d" cx="'+x(p)+'" cy="'+y(p)+'"/></g>').join('');
      chart='<svg class="history-chart" viewBox="0 0 900 330" aria-label="'+esc(data.title)+'; discrete reported values, no interpolation">'+grid+marks+labels.map(p=>'<text x="'+x(p)+'" y="'+Math.max(22,y(p)-18)+'" text-anchor="middle">'+fmt(p.value)+'</text>').join('')+'<text x="70" y="300">'+esc(rows[0].period)+'</text><text x="830" y="300" text-anchor="end">'+esc(rows.at(-1).period)+'</text></svg><p id="history-hover" role="status">Hover, tap or focus a point to inspect its period, cases and source.</p>';
    }
    el('result').innerHTML='<h3>'+esc(data.title)+' · '+esc(data.geography)+'</h3><p>'+esc(data.limitations)+'</p><p>Source: <a href="'+esc(data.source_url)+'" target="_blank" rel="noopener">'+esc(data.source)+' →</a> · Retrieved '+esc(new Date(data.retrieved_at).toLocaleString())+' · Publication date not supplied in this archive.</p>'+(data.summary?.total!=null?'<div class="history-summary"><strong>'+fmt(data.summary.total)+'</strong><span>'+esc(data.summary.label)+'</span><small>'+data.summary.count+' of '+data.summary.expected+' requested '+esc(data.frequency)+' periods reported. '+esc(data.summary.note)+'</small></div>':'')+(valid.length?chart:'<p>'+esc(data.empty_message)+'</p>')+'<div class="history-actions"><button id="history-ask">Ask about this history</button><button id="history-csv">Download historical CSV</button></div><details><summary>Accessible history and provenance table ('+rows.length+' rows)</summary><div class="epi-scroll"><table><thead><tr><th>Period / outbreak</th><th>Value</th><th>Status</th><th>Evidence</th></tr></thead><tbody>'+rows.map(p=>'<tr><td>'+esc(p.label||p.period)+'</td><td>'+(p.value==null?'No reported value':fmt(p.value))+'</td><td>'+esc(p.status)+'</td><td><a href="'+esc(p.source_url||data.source_url)+'" target="_blank" rel="noopener">Original source</a><small>'+esc(p.evidence_id)+'</small></td></tr>').join('')+'</tbody></table></div></details>';
    if(window.renderHistoryHeatmap)el('result').querySelector('.history-actions').insertAdjacentHTML('beforebegin',window.renderHistoryHeatmap(data));
    el('ask').onclick=()=>{const context={threat_id:data.disease||data.threat,disease:data.disease||data.threat,geography:data.geography,visual:'historical_archive',visual_title:data.title,visual_context:{dataset:data.threat,country:data.country,start:data.start,end:data.end}};contextualAsk('Summarize this historical evidence.',context);document.querySelector('#ask')?.scrollIntoView({behavior:'smooth'})};
    el('csv').onclick=()=>{const fields=['period','label','value','status','evidence_id'];const csv=[fields.concat(['source_url','retrieved_at']),...rows.map(p=>fields.map(k=>p[k]??'').concat([p.source_url||data.source_url,data.retrieved_at]))].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='fynura-'+data.threat+'-history.csv';a.click();URL.revokeObjectURL(u)};
    el('result').querySelectorAll('[data-history-point]').forEach(mark=>{const show=()=>{const p=valid[Number(mark.dataset.historyPoint)];el('hover').textContent=p.period+' · '+fmt(p.value)+' '+data.unit+' · '+data.frequency+' · '+data.geography+' · '+data.source};mark.onmouseenter=show;mark.onfocus=show;mark.onclick=show});
  }
  el('load').onclick=load;el('country').onchange=load;el('disease').onchange=scope;
  fetch('/api/history').then(r=>{if(!r.ok)throw Error('History unavailable. Please sign in again if your session expired.');return r.json()}).then(d=>{meta=d;scope()}).catch(e=>el('status').textContent=e.message);
})();
