/* Public analytics are derived from the same canonical snapshots as Ask and maps. */
(() => {
  const historyStyle=document.createElement('link');historyStyle.rel='stylesheet';historyStyle.href='/static/history-polish.css?v=2';document.head.append(historyStyle);
  const historyScript=document.createElement('script');historyScript.src='/static/history.js?v=1';document.head.append(historyScript);
  const chartScript=document.createElement('script');chartScript.src='/static/trajectory.js?v=1';chartScript.onload=()=>{const shared=document.createElement('script');shared.src='/static/workspace.js?v=1';document.head.append(shared)};document.head.append(chartScript);
  const dateLabel = v => v ? new Date(v+'T00:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}) : 'Not stated';
  async function sourceHealth(){
    const r=await fetch('/api/data-status');if(!r.ok)return;const data=await r.json();
    const pulse=document.querySelector('#pulse');
    pulse.onclick=()=>{const panel=document.querySelector('#health');panel.hidden=!panel.hidden;panel.innerHTML=`<div><strong>GLOBAL EVIDENCE NETWORK</strong><button aria-label="Close source status">×</button></div><dl>${data.network.map(s=>`<dt>${safe(s.name)}</dt><dd>${safe(s.status)}</dd>`).join('')}</dl><p>${data.threats_monitored} threats monitored · ${data.verified_snapshots} verified snapshots</p><p>Last intelligence check: ${safe(Object.values(data.refresh).map(x=>x.last_check).filter(Boolean).sort().at(-1)||'Not recorded')}</p><a href="#sources">Explore sources →</a>`;panel.querySelector('button').onclick=()=>panel.hidden=true};
    const label=pulse.querySelector('small');if(label)label.textContent='Verified evidence network';
  }
  async function analytics(){
    const r=await fetch('/api/analytics');if(!r.ok)return;const rows=await r.json();if(!rows.length)return;
    let panel=document.querySelector('#epi-intelligence');if(!panel){panel=document.createElement('section');panel.id='epi-intelligence';panel.className='epi-panel';document.querySelector('#visuals').before(panel)}
    panel.innerHTML=`<small>EPIDEMIOLOGICAL INTELLIGENCE</small><h2>Evidence in perspective.</h2><p>Compatible observations only. Missing values are never treated as zero.</p><div class="epi-controls"><input type="search" aria-label="Filter epidemiological snapshot" placeholder="Search threat or geography"><button id="epi-csv">Download CSV</button></div><div class="epi-scroll"><table><caption>Verified epidemiological snapshot. Select a threat to update the map and question context.</caption><thead><tr>${['Threat','Geography','Cases','Deaths','CFR','Change','Reporting cutoff','Evidence'].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody></tbody></table></div><p>IFR: Not estimable from current surveillance data. Infection fatality ratio requires total infections, not only reported cases.</p><h3>Early signal detection</h3><p>Statistical surveillance, not outbreak forecasting. <a href="/docs#early-signals">View method →</a></p><div class="early-grid">${rows.map(x=>`<article><small>${safe(x.threat.toUpperCase())} · ${safe(x.geography)}</small><strong>${safe(x.early_signal.signal)}</strong><p>${safe(x.early_signal.reasons.join(' '))}</p><p>No statistical alert is inferred from a short report sequence.</p><button data-epi="${safe(x.threat)}">View evidence</button></article>`).join('')}</div>`;
    const render=()=>{const query=panel.querySelector('input').value.toLowerCase();panel.querySelector('tbody').innerHTML=rows.filter(x=>(x.threat+' '+x.geography).toLowerCase().includes(query)).map(x=>`<tr><td><button data-select="${safe(x.threat)}">${safe(x.threat)}</button></td><td>${safe(x.geography)}</td><td>${fmt(x.cases)}</td><td>${x.deaths==null?'Not available':fmt(x.deaths)}</td><td title="Fynura-computed crude CFR">${x.cfr==null?'Not estimable':x.cfr.toFixed(2)+'%'}</td><td>${x.change==null?'Not comparable':fmt(x.change)}</td><td>${dateLabel(x.reporting_cutoff)}</td><td><button data-epi="${safe(x.threat)}">Inspect</button></td></tr>`).join('');wire()};
    const wire=()=>{panel.querySelectorAll('[data-epi]').forEach(b=>b.onclick=()=>{const a=intel.data[b.dataset.epi];if(a){evidence(a);document.querySelector('#drawer').showModal()}});panel.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{setContext(contextFor(b.dataset.select));document.querySelector('#map-disease').value=b.dataset.select;document.querySelector('#map-disease').dispatchEvent(new Event('change'));showVisual(b.dataset.select)})};
    panel.querySelector('input').oninput=render;render();
    panel.querySelector('#epi-csv').onclick=()=>{const fields=['threat','geography','cases','deaths','cfr','change','reporting_cutoff','source_url'];const csv=[fields,...rows.map(x=>fields.map(k=>x[k]??''))].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='fynura-epidemiological-snapshot.csv';a.click();URL.revokeObjectURL(url)};
  }
  window.addEventListener('fynura:intelligence',()=>{analytics().catch(()=>{});sourceHealth().catch(()=>{})});
  sourceHealth().catch(()=>{});if(Object.keys(intel.data).length)analytics().catch(()=>{});
})();
