const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = {window:{}, safe:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'), fmt:n=>String(n)};
vm.createContext(context);
vm.runInContext(fs.readFileSync('frontend/history-heatmap.js','utf8'),context);
const render=context.window.renderHistoryHeatmap;
const series={frequency:'monthly',start:2020,end:2020,geography:'Test <country>',unit:'cases',source:'WHO',source_url:'https://www.who.int/',retrieved_at:'2026-08-30',points:[{period:'2020-01',value:0},{period:'2020-03',value:100}]};
const chart=render(series);
assert.equal((chart.match(/role="img"/g)||[]).length,12);
assert.ok(chart.includes('2020-01 · 0 cases'));
assert.ok(chart.includes('2020-02 · No reported value'));
assert.ok(chart.includes('Test &lt;country>'));
assert.ok(!chart.includes('vaccine effectiveness'));
assert.ok(chart.includes('Darker cells indicate higher reported counts'));
assert.equal(render({...series,frequency:'outbreak'}),'');
assert.equal(render({...series,points:[]}), '');
const annual=render({...series,frequency:'annual',points:[{period:'2020',value:100}]});
assert.equal((annual.match(/role="img"/g)||[]).length,1);
console.log('Heatmap checks passed: missing/zero, escaping, annual/monthly, outbreak exclusion.');
